version: 2
jobs:
  build.lts:
    docker:
      - image: "ubuntu:latest"
    steps:
      - run:
          name: Reloading apt indexes
          command: 'apt-get update'
      - run:
          name: Installing git
          command: 'apt-get install -y git'
      - checkout
      - run:
          name: Downloading submodules
          command: 'git submodule update --init --recursive --depth 1'
      - run:
          name: Installing deps
          command: './.circleci/install-deps.sh'
      - run:
          name: Building, installing, creating package
          command: './.circleci/do-build.sh'
      - run:
          name: Preparing artifacts
          command: './.circleci/prepare-artifacts.sh'
      - persist_to_workspace:
          root: /tmp/artifacts
          paths: './*.deb'

  build.rolling:
    docker:
      - image: "ubuntu:rolling"
    steps:
      - run:
          name: Reloading apt indexes
          command: 'apt-get update'
      - run:
          name: Installing git
          command: 'apt-get install -y git'
      - checkout
      - run:
          name: Downloading submodules
          command: 'git submodule update --init --recursive --depth 1'
      - run:
          name: Installing deps
          command: './.circleci/install-deps.sh'
      - run:
          name: Building, installing, creating package
          command: './.circleci/do-build.sh'
      - run:
          name: Preparing artifacts
          command: './.circleci/prepare-artifacts.sh'
      - persist_to_workspace:
          root: /tmp/artifacts
          paths: './*.deb'

  artifacts:
    docker:
      - image: "ubuntu:rolling"
    steps:
      - run: apt-get update
      - run: apt-get install -y ca-certificates
      - attach_workspace:
          at: /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts

  deploy:
    docker:
      - image: "ubuntu:rolling"
    environment:
      MNTDIR: '/tmp/ftp'
    steps:
      - run: apt-get update
      - run: apt-get install -y curlftpfs
      - attach_workspace:
          at: /tmp/artifacts
      - run:
          name: Creating mount point
          command: 'mkdir "$MNTDIR"'
      - run:
          name: Mounting directory
          command: 'echo "$FTP_PASSWORD" | curlftpfs "$FTP_SERVER" "$MNTDIR" -o "user=$FTP_USER"'
      - run:
          name: Cleaning old files
          command: 'rm -r "${MNTDIR}/*"'
      - run:
          name: Uploading artifacts
          command: 'cp -r /tmp/artifacts/* "$MNTDIR"'
      - run:
          name: Unmounting
          command: 'fusermount -u "$MNTDIR"'

workflows:
  version: 2
  build-all:
    jobs:
      - build.lts
      - build.rolling
      - artifacts:
          requires:
            - build.lts
            - build.rolling
      - deploy:
          requires:
            - build.lts
            - build.rolling
          filters:
            branches:
              only: master
