version: 2
jobs:
  build.lts:
    docker:
      - image: "ubuntu:latest"
    steps:
      - run:
          name: Reloading apt indexes
          command: 'apt-get update'
      - run:
          name: Installing git
          command: 'apt-get install -y git'
      - checkout
      - run:
          name: Downloading submodules
          command: 'git submodule update --init --recursive --depth 1'
      - run:
          name: Installing deps
          command: './.circleci/install-deps.sh'
      - run:
          name: Building, installing, creating package
          command: './.circleci/do-build.sh'
      - run:
          name: Preparing artifacts
          command: './.circleci/prepare-artifacts.sh'
      - persist_to_workspace:
          root: /tmp/artifacts
          paths: './*'

  build.rolling:
    docker:
      - image: "ubuntu:rolling"
    steps:
      - run:
          name: Reloading apt indexes
          command: 'apt-get update'
      - run:
          name: Installing git
          command: 'apt-get install -y git'
      - checkout
      - run:
          name: Downloading submodules
          command: 'git submodule update --init --recursive --depth 1'
      - run:
          name: Installing deps
          command: './.circleci/install-deps.sh'
      - run:
          name: Building, installing, creating package
          command: './.circleci/do-build.sh'
      - run:
          name: Building and creating .tar.gz archive
          command: './.circleci/pack-tgz.sh'
      - run:
          name: Preparing artifacts
          command: './.circleci/prepare-artifacts.sh'
      - persist_to_workspace:
          root: /tmp/artifacts
          paths: './*'

  artifacts:
    docker:
      - image: "ubuntu:rolling"
    steps:
      - run: apt-get update
      - run: apt-get install -y ca-certificates
      - attach_workspace:
          at: /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts

  deploy:
    docker:
      - image: "ubuntu:rolling"
    steps:
      - run: apt-get update
      - run: apt-get install -y ca-certificates lftp
      - attach_workspace:
          at: /tmp/artifacts
      - run:
          name: Working with FTP
          command: |
            lftp -d $FTP_SERVER <<EOF
            user $FTP_USER $FTP_PASSWORD
            set ftp:ssl-allow no
            mirror --reverse --only-missing --delete-first /tmp/artifacts /
            bye
            EOF

workflows:
  version: 2
  build-all:
    jobs:
      - build.lts
      - build.rolling
      - artifacts:
          requires:
            - build.lts
            - build.rolling
      - deploy:
          requires:
            - build.lts
            - build.rolling
          filters:
            branches:
              only: master
