version: 2
jobs:
  build.lts:
    docker:
      - image: "ubuntu:latest"
    steps:
      - run:
          name: Reloading apt indexes
          command: 'apt-get update'
      - run:
          name: Installing git
          command: 'apt-get install -y git'
      - checkout
      - run:
          name: Downloading submodules
          command: 'git submodule update --init --recursive --depth 1'
      - run:
          name: Installing Clang
          command: 'apt-get install -y clang'
      - run:
          name: Installing CMake
          command: 'apt-get install -y extra-cmake-modules cmake'
      - run:
          name: Installing cubosphere deps
          command: 'apt-get install -y libglvnd-dev liblua5.1-0-dev libglew-dev libjpeg-turbo8-dev libsdl1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev'
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild -DCMAKE_CXX_COMPILER=clang++'
      - run:
          name: Building
          command: 'cmake --build build -- -j4'
      - run:
          name: Installing
          command: 'cmake --build build --target install'
  build.rolling:
    docker:
      - image: "ubuntu:rolling"
    steps:
      - run:
          name: Reloading apt indexes
          command: 'apt-get update'
      - run:
          name: Installing git
          command: 'apt-get install -y git'
      - checkout
      - run:
          name: Downloading submodules
          command: 'git submodule update --init --recursive --depth 1'
      - run:
          name: Installing Clang
          command: 'apt-get install -y clang'
      - run:
          name: Installing CMake
          command: 'apt-get install -y extra-cmake-modules cmake'
      - run:
          name: Installing cubosphere deps
          command: 'apt-get install -y libglvnd-dev liblua5.1-0-dev libglew-dev libjpeg-turbo8-dev libsdl1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev'
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild -DCMAKE_CXX_COMPILER=clang++'
      - run:
          name: Building
          command: 'cmake --build build -- -j4'
      - run:
          name: Installing
          command: 'cmake --build build --target install'

workflows:
  version: 2
  build-all:
    jobs:
      build.lts
      build.rolling
