version: 2
jobs:
  build.lts:
    docker:
      - image: "ubuntu:latest"
    steps:
      - run:
          name: Reloading apt indexes
          command: 'apt-get update'
      - run:
          name: Installing git
          command: 'apt-get install -y git'
      - checkout
      - run:
          name: Downloading submodules
          command: 'git submodule update --init --recursive --depth 1'
      - run:
          name: Installing deps
          command: './.circleci/install-deps.sh'
      - run:
          name: Building, installing, creating package
          command: './.circleci/do-build.sh'
      - run:
          name: Preparing artifacts
          command: './.circleci/do-build.sh'
      - store_artifacts:
          path: /tmp/artifacts

  build.rolling:
    docker:
      - image: "ubuntu:rolling"
    steps:
      - run:
          name: Reloading apt indexes
          command: 'apt-get update'
      - run:
          name: Installing git
          command: 'apt-get install -y git'
      - checkout
      - run:
          name: Downloading submodules
          command: 'git submodule update --init --recursive --depth 1'
      - run:
          name: Installing deps
          command: './.circleci/install-deps.sh'
      - run:
          name: Building, installing, creating package
          command: './.circleci/do-build.sh'
      - run:
          name: Preparing artifacts
          command: './.circleci/do-build.sh'
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  build-all:
    jobs:
      - build.lts
      - build.rolling
